steps:
  # Web
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'asia-northeast3-docker.pkg.dev/tech-docs-408301/tech-docs-web/production',
        '-f',
        './Dockerfile',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      ['push', 'asia-northeast3-docker.pkg.dev/tech-docs-408301/tech-docs-web/production']