services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    command: yarn dev
    env_file:
      - .env
    ports:
      - '8000:3000'
    volumes:
      - .:/usr/src/app
