apiVersion: v1
kind: Service
metadata:
  labels:
    app: tech-docs-web
  name: tech-docs-web
spec:
  ports:
  - name: "http"
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: tech-docs-web
  type: NodePort
